table _measures
	lineageTag: 0165d7ac-b476-4d47-97bc-30f9c02c21fa
	sourceLineageTag: [dbo].[_measures]

	measure 'Dynamic Text/Title (Multi-Select) - Filter Selections' = ```
			-- Configuration constants
			VAR LineBreak = UNICHAR(10)
			VAR ExcludeThreshold = 3  -- Show "excluding" format when 3 or fewer items are unselected
			VAR MaxDisplayItems = 4   -- Maximum items to show before truncating with "and X more"
			
			-- Location filtering logic with enhanced length management
			VAR IsCountryFiltered = ISFILTERED('vw_dim_customers'[country])
			VAR IsCityFiltered = ISFILTERED('vw_dim_customers'[city])
			
			VAR SelectedLocation = 
			    IF(IsCountryFiltered,
			        -- Region is filtered, check state logic
			        IF(IsCityFiltered,
			            -- Both Region and State are filtered
			            VAR AllCitiesInCountry = CALCULATETABLE(
			                VALUES('vw_dim_customers'[city]),
			                ALLEXCEPT('vw_dim_customers', 'vw_dim_customers'[country])
			            )
			            VAR SelectedCities = VALUES('vw_dim_customers'[city])
			            VAR UnselectedCities = EXCEPT(AllCitiesInCountry, SelectedCities)
			            VAR UnselectedCitiesCount = COUNTROWS(UnselectedCities)
			            VAR TotalCitiesInCountry = COUNTROWS(AllCitiesInCountry)
			            VAR SelectedCitiesCount = COUNTROWS(SelectedCities)
			            VAR SelectedCity = CONCATENATEX(VALUES('vw_dim_customers'[country]), 'vw_dim_customers'[country], ", ")
			            
			            VAR LocationResult = 
			                IF(UnselectedCitiesCount = 0,
			                    -- All states selected, show only region
			                    SelectedCity,
			                    IF(UnselectedCitiesCount <= ExcludeThreshold && UnselectedCitiesCount < TotalCitiesInCountry,
			                        -- Few states unselected, show "excluding" format
			                        SelectedCity & " (excluding " & CONCATENATEX(UnselectedCities, 'vw_dim_customers'[city], ", ") & ")",
			                        -- Many states unselected, check if we should truncate selected states
			                        IF(SelectedCitiesCount <= MaxDisplayItems,
			                            -- Show all selected states
			                            SelectedCity & " - " & CONCATENATEX(SelectedCities, 'vw_dim_customers'[city], ", "),
			                            -- Truncate with "and X more" format
			                            VAR FirstStates = CONCATENATEX(
			                                TOPN(MaxDisplayItems, SelectedCities, 'vw_dim_customers'[city], ASC),
			                                'vw_dim_customers'[city], ", "
			                            )
			                            VAR RemainingCount = SelectedCitiesCount - MaxDisplayItems
			                            RETURN SelectedCity & " - " & FirstStates & " and " & RemainingCount & " more"
			                        )
			                    )
			                )
			            RETURN LocationResult,
			            
			            -- Only Region filtered
			            VAR SelectedCityCount = COUNTROWS(VALUES('vw_dim_customers'[country]))
			            VAR RegionText = CONCATENATEX(VALUES('vw_dim_customers'[country]), 'vw_dim_customers'[country], ", ")
			            RETURN 
			                IF(SelectedCityCount <= MaxDisplayItems,
			                    RegionText,
			                    VAR FirstRegions = CONCATENATEX(
			                        TOPN(MaxDisplayItems, VALUES('vw_dim_customers'[country]), 'vw_dim_customers'[country], ASC),
			                        'vw_dim_customers'[country], ", "
			                    )
			                    VAR RemainingRegions = SelectedCityCount - MaxDisplayItems
			                    RETURN FirstRegions & " and " & RemainingRegions & " more"
			                )
			        ),
			        IF(IsCityFiltered,
			            -- Only State filtered
			            VAR SelectedCitiesCount = COUNTROWS(VALUES('vw_dim_customers'[city]))
			            VAR StateText = CONCATENATEX(VALUES('vw_dim_customers'[city]), 'vw_dim_customers'[city], ", ")
			            RETURN 
			                IF(SelectedCitiesCount <= MaxDisplayItems,
			                    StateText,
			                    VAR FirstStates = CONCATENATEX(
			                        TOPN(MaxDisplayItems, VALUES('vw_dim_customers'[city]), 'vw_dim_customers'[city], ASC),
			                        'vw_dim_customers'[city], ", "
			                    )
			                    VAR RemainingStates = SelectedCitiesCount - MaxDisplayItems
			                    RETURN FirstStates & " and " & RemainingStates & " more"
			                ),
			            
			            -- No location filter
			            "All Locations"
			        )
			    )
			
			
			-- Category filtering logic with enhanced length management
			VAR IsCategoryFiltered = ISFILTERED('vw_dim_products'[category])
			VAR IsSubCategoryFiltered = ISFILTERED('vw_dim_products'[subcategory])
			
			VAR SelectedCategory = 
			    IF(IsCategoryFiltered,
			        -- Category is filtered, check sub-category logic
			        IF(IsSubCategoryFiltered,
			            -- Both Category and Sub-Category are filtered
			            VAR AllSubCategoriesInCategory = CALCULATETABLE(
			                VALUES('vw_dim_products'[subcategory]),
			                ALLEXCEPT('vw_dim_products', 'vw_dim_products'[category])
			            )
			            VAR SelectedSubCategories = VALUES('vw_dim_products'[subcategory])
			            VAR UnselectedSubCategories = EXCEPT(AllSubCategoriesInCategory, SelectedSubCategories)
			            VAR UnselectedSubCount = COUNTROWS(UnselectedSubCategories)
			            VAR TotalSubCategoriesInCategory = COUNTROWS(AllSubCategoriesInCategory)
			            VAR SelectedSubCount = COUNTROWS(SelectedSubCategories)
			            VAR SelectedCategoryText = CONCATENATEX(VALUES('vw_dim_products'[category]), 'vw_dim_products'[category], ", ")
			            
			            VAR CategoryResult = 
			                IF(UnselectedSubCount = 0,
			                    -- All sub-categories selected, show only category
			                    SelectedCategoryText,
			                    IF(UnselectedSubCount <= ExcludeThreshold && UnselectedSubCount < TotalSubCategoriesInCategory,
			                        -- Few sub-categories unselected, show "excluding" format
			                        SelectedCategoryText & " (excluding " & CONCATENATEX(UnselectedSubCategories, 'vw_dim_products'[subcategory], ", ") & ")",
			                        -- Many sub-categories unselected, check if we should truncate
			                        IF(SelectedSubCount <= MaxDisplayItems,
			                            -- Show all selected sub-categories
			                            SelectedCategoryText & " - " & CONCATENATEX(SelectedSubCategories, 'vw_dim_products'[subcategory], ", "),
			                            -- Truncate with "and X more" format
			                            VAR FirstSubCategories = CONCATENATEX(
			                                TOPN(MaxDisplayItems, SelectedSubCategories, 'vw_dim_products'[subcategory], ASC),
			                                'vw_dim_products'[subcategory], ", "
			                            )
			                            VAR RemainingSubCount = SelectedSubCount - MaxDisplayItems
			                            RETURN SelectedCategoryText & " - " & FirstSubCategories & " and " & RemainingSubCount & " more"
			                        )
			                    )
			                )
			            RETURN CategoryResult,
			            
			            -- Only Category filtered
			            VAR SelectedCategoryCount = COUNTROWS(VALUES('vw_dim_products'[category]))
			            VAR CategoryText = CONCATENATEX(VALUES('vw_dim_products'[category]), 'vw_dim_products'[category], ", ")
			            RETURN CategoryText
			        ),
			        IF(IsSubCategoryFiltered,
			            -- Only Sub-Category filtered
			            VAR SelectedSubCount = COUNTROWS(VALUES('vw_dim_products'[subcategory]))
			            VAR SubCategoryText = CONCATENATEX(VALUES('vw_dim_products'[subcategory]), 'vw_dim_products'[subcategory], ", ")
			            RETURN 
			                IF(SelectedSubCount <= MaxDisplayItems,
			                    SubCategoryText,
			                    VAR FirstSubCategories = CONCATENATEX(
			                        TOPN(MaxDisplayItems, VALUES('vw_dim_products'[subcategory]), 'vw_dim_products'[subcategory], ASC),
			                        'vw_dim_products'[subcategory], ", "
			                    )
			                    VAR RemainingSubCount = SelectedSubCount - MaxDisplayItems
			                    RETURN FirstSubCategories & " and " & RemainingSubCount & " more"
			                ),
			            
			            -- No category filter
			            "All Categories"
			        )
			    )
			
			-- Year filtering logic
			VAR SelectedYear = SELECTEDVALUE('Dates'[Year], "All Years")
			
			-- Return multi-line format consistently
			RETURN 
			    "Year: " & SelectedYear & LineBreak & 
			    "Location: " & SelectedLocation & LineBreak & 
			    "Category: " & SelectedCategory
			
			```
		lineageTag: 5af6b464-66dc-41d4-91a8-96ddb7226957

	measure '_01 Total Transactions' = ```
			DISTINCTCOUNT(vw_fact_sales[order_number])
			
			
			```
		formatString: 0
		lineageTag: abb3d804-7dcc-49c0-bb64-d6009c80230e

	measure '_02 PY Total Transactions' = ```
			
			IF(
			    HASONEVALUE(Dates[Year]),
			    CALCULATE(
			        [_01 Total Transactions],
			        SAMEPERIODLASTYEAR(Dates[Date])
			    ),
			    BLANK()
			)
			
			
			```
		formatString: 0
		lineageTag: 0860a5c4-28ba-479a-bcc7-ec921c4c75c2

	measure '_02 PM Total Transactions' = ```
			
			IF(
			    HASONEVALUE(Dates[Year]),
			    CALCULATE(
			        [_01 Total Transactions],
			        DATEADD(Dates[Date],-1,MONTH)
			    ),
			    BLANK()
			)
			
			
			```
		formatString: 0
		lineageTag: fa5fc320-87fd-42e7-ad81-062f89f81dc3

	measure '_03 △PY Total Transactions' = ```
			
			IF(
			    HASONEVALUE(Dates[Year]) 
			    && NOT(ISBLANK([_02 PY Total Transactions])) 
			    && NOT(ISBLANK([_01 Total Transactions])) 
			    && [_01 Total Transactions] <> 0,
			    [_01 Total Transactions] - [_02 PY Total Transactions],
			    BLANK()
			)
			
			
			```
		formatString: 0
		lineageTag: 02a4fc91-b67c-425d-9727-33471f3eb7d7

	measure '_04 △PM% Total Transactions' = ```
			
			IF(
			    ISBLANK([_01 Total Transactions]) || [_01 Total Transactions] = 0,
			    "--",
			    DIVIDE([_01 Total Transactions] - [_02 PM Total Transactions], [_02 PM Total Transactions], 0)
			)
			
			
			```
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 91983c98-cdec-4c77-bac1-04c7f149d549

	measure '_04 △PY% Total Transactions' = ```
			
			IF(
			    ISBLANK([_01 Total Transactions]) || [_01 Total Transactions] = 0,
			    "--",
			    DIVIDE([_01 Total Transactions] - [_02 PY Total Transactions], [_02 PY Total Transactions], 0)
			)
			
			
			```
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 6ae3251f-6805-43e0-b3b6-81be5894d3d7

	measure '_05 CF_△PM% Total Transactions' = ```
			
			SWITCH(
			    TRUE(),
			    [_04 △PM% Total Transactions] > 0, "#6A994E",
			    [_04 △PM% Total Transactions] = 0, "#808080",
			    "#BC4749"
			)
				
			
			```
		lineageTag: b8facb4b-6ba9-4b03-83a6-7436024da89d

	measure '_05 CF_△PY% Total Transactions' = ```
			
			SWITCH(
			    TRUE(),
			    [_04 △PY% Total Transactions] > 0, "#6A994E",
			    [_04 △PY% Total Transactions] = 0, "#808080",
			    "#BC4749"
			)
				
			
			```
		lineageTag: edba1194-1109-4afc-bac6-b978189d1a72

	measure '_01 AC Total Transactions (DayNum)' = ```
			
			SUMX(
			    VALUES(Dates[Day]),  -- Ensures daynum remain visible
			    VAR TransactionsAC = COALESCE([_01 Total Transactions], 0)
			    RETURN 
			        TransactionsAC  -- Keeps 0 values visible
			)
				
			
			```
		formatString: 0
		lineageTag: 08a3845b-ad02-4d25-9ed6-0b7c62690c5b

	measure '_01 Total Revenue' = ```
			SUM(vw_fact_sales[revenue])
				
			
			```
		formatString: 0
		lineageTag: a6d33f59-efda-4f29-ac11-6e20581ae71b

	measure '_02 PY Total Revenue' = ```
			
			IF(
			    HASONEVALUE(Dates[Year]),
			    CALCULATE(
			        [_01 Total Revenue],
			        SAMEPERIODLASTYEAR(Dates[Date])
			    ),
			    BLANK()
			)
			
			
			```
		formatString: 0
		lineageTag: 353c7845-dba8-4468-af0a-b3d5208a7eb9

	measure '_02 PM Total Revenue' = ```
			
			IF(
			    HASONEVALUE(Dates[Year]),
			    CALCULATE(
			        [_01 Total Revenue],
			        DATEADD(Dates[Date],-1,MONTH)
			    ),
			    BLANK()
			)
				
			
			```
		formatString: 0
		lineageTag: 300033e7-975b-408b-9cc8-0325be39d56a

	measure '_03 △PY Total Revenue' = ```
			
			IF(
			    HASONEVALUE(Dates[Year]) 
			    && NOT(ISBLANK([_02 PY Total Revenue])) 
			    && NOT(ISBLANK([_01 Total Revenue])) 
			    && [_01 Total Revenue] <> 0,
			    [_01 Total Revenue] - [_02 PY Total Revenue],
			    BLANK()
			)
				
			
			```
		formatString: 0
		lineageTag: 20503cdb-739e-4943-82ea-6c9a51aae36c

	measure '_04 △PM% Total Revenue' = ```
			
			IF(
			    ISBLANK([_01 Total Revenue]) || [_01 Total Revenue] = 0,
			    "--",
			    DIVIDE([_01 Total Revenue] - [_02 PM Total Revenue], [_02 PM Total Revenue], 0)
			)
				
			
			```
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 16b00180-027b-4fb9-9d87-466857b2a488

	measure '_04 △PY% Total Revenue' = ```
			
			IF(
			    ISBLANK([_01 Total Revenue]) || [_01 Total Revenue] = 0,
			    "--",
			    DIVIDE([_01 Total Revenue] - [_02 PY Total Revenue], [_02 PY Total Revenue], 0)
			)
				
			
			```
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 9b3d167a-6023-400d-8719-c98dfe5e8e00

	measure '_05 CF_△PM% Total Revenue' = ```
			
			SWITCH(
			    TRUE(),
			    [_04 △PM% Total Revenue] > 0, "#6A994E",
			    [_04 △PM% Total Revenue] = 0, "#808080",
			    "#BC4749"
			)
				
			
			```
		lineageTag: debd470d-d8f1-4f47-8948-652aeb9ebd9e

	measure '_05 CF_△PY% Total Revenue' = ```
			
			SWITCH(
			    TRUE(),
			    [_04 △PY% Total Revenue] > 0, "#6A994E",
			    [_04 △PY% Total Revenue] = 0, "#808080",
			    "#BC4749"
			)
				
			
			```
		lineageTag: 17ad4e6f-be8e-4199-a62b-353d4b91774a

	measure '_01 AC Total Revenue (DayNum)' = ```
			
			SUMX(
			    VALUES(Dates[Day]),  -- Ensures daynum remain visible
			    VAR TransactionsAC = COALESCE([_01 Total Revenue], 0)
			    RETURN 
			        TransactionsAC  -- Keeps 0 values visible
			)
				
			
			```
		formatString: 0
		lineageTag: be6ff18f-c294-40e6-9c38-fbd6282f0529

	measure '_01 Total Profit' = ```
			SUM(vw_fact_sales[profit])
				
			
			```
		formatString: 0
		lineageTag: 2bf8214c-8779-4e9b-8130-a063fcf3334a

	measure '_02 PY Total Profit' = ```
			
			IF(
			    HASONEVALUE(Dates[Year]),
			    CALCULATE(
			        [_01 Total Profit],
			        SAMEPERIODLASTYEAR(Dates[Date])
			    ),
			    BLANK()
			)
			
			
			```
		formatString: 0
		lineageTag: 49295833-cf78-460a-a756-012feab0ac46

	measure '_02 PM Total Profit' = ```
			
			IF(
			    HASONEVALUE(Dates[Year]),
			    CALCULATE(
			        [_01 Total Profit],
			        DATEADD(Dates[Date],-1,MONTH)
			    ),
			    BLANK()
			)
				
			
			```
		formatString: 0
		lineageTag: 7a126688-ba2b-436b-859a-0e8e8cd015e9

	measure '_03 △PY Total Profit' = ```
			
			IF(
			    HASONEVALUE(Dates[Year]) 
			    && NOT(ISBLANK([_02 PY Total Profit])) 
			    && NOT(ISBLANK([_01 Total Profit])) 
			    && [_01 Total Profit] <> 0,
			    [_01 Total Profit] - [_02 PY Total Profit],
			    BLANK()
			)
				
			
			```
		formatString: 0
		lineageTag: f3879d27-3f09-4cd3-9069-06a6a44b6f76

	measure '_04 △PM% Total Profit' = ```
			
			IF(
			    ISBLANK([_01 Total Profit]) || [_01 Total Profit] = 0,
			    "--",
			    DIVIDE([_01 Total Profit] - [_02 PM Total Profit], [_02 PM Total Profit], 0)
			)
				
			
			```
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 73609156-384c-4ef9-8dd1-dc026dcc7a4e

	measure '_04 △PY% Total Profit' = ```
			
			IF(
			    ISBLANK([_01 Total Profit]) || [_01 Total Profit] = 0,
			    "--",
			    DIVIDE([_01 Total Profit] - [_02 PY Total Profit], [_02 PY Total Profit], 0)
			)
				
			
			```
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 3fc782ac-dfa1-4b28-9b58-af8fd968037e

	measure '_05 CF_△PM% Total Profit' = ```
			
			SWITCH(
			    TRUE(),
			    [_04 △PM% Total Profit] > 0, "#6A994E",
			    [_04 △PM% Total Profit] = 0, "#808080",
			    "#BC4749"
			)
				
			
			```
		lineageTag: 3daf68b1-c7e4-4a42-b36f-c8bd9f212ea7

	measure '_05 CF_△PY% Total Profit' = ```
			
			SWITCH(
			    TRUE(),
			    [_04 △PY% Total Profit] > 0, "#6A994E",
			    [_04 △PY% Total Profit] = 0, "#808080",
			    "#BC4749"
			)
				
			
			```
		lineageTag: f5e26c8e-5f43-4724-b2f8-7aa5dfbf2d2d

	measure '_01 AC Total Profit (DayNum)' = ```
			
			SUMX(
			    VALUES(Dates[Day]),  -- Ensures daynum remain visible
			    VAR TransactionsAC = COALESCE([_01 Total Profit], 0)
			    RETURN 
			        TransactionsAC  -- Keeps 0 values visible
			)
			
			
			```
		formatString: 0
		lineageTag: f9aa21a5-2033-4bef-8559-222b7776cc51

	measure '_01 Total Quantity' = ```
			SUM(vw_fact_sales[quantity])
			
			
			```
		formatString: 0
		lineageTag: 961972aa-8f6b-4035-849d-1bac5d044eb5

	measure '_02 PY Total Quantity' = ```
			
			IF(
			    HASONEVALUE(Dates[Year]),
			    CALCULATE(
			        [_01 Total Quantity],
			        SAMEPERIODLASTYEAR(Dates[Date])
			    ),
			    BLANK()
			)
			
			
			```
		formatString: 0
		lineageTag: b7efb854-5af3-4fe7-9922-2dcd2e0628af

	measure '_02 PM Total Quantity' = ```
			
			IF(
			    HASONEVALUE(Dates[Year]),
			    CALCULATE(
			        [_01 Total Quantity],
			        DATEADD(Dates[Date],-1,MONTH)
			    ),
			    BLANK()
			)
			
			
			```
		formatString: 0
		lineageTag: 101f4ce5-dc41-4b8d-bfc1-e94e61d1d715

	measure '_03 △PY Total Quantity' = ```
			
			IF(
			    HASONEVALUE(Dates[Year]) 
			    && NOT(ISBLANK([_02 PY Total Quantity])) 
			    && NOT(ISBLANK([_01 Total Quantity])) 
			    && [_01 Total Quantity] <> 0,
			    [_01 Total Quantity] - [_02 PY Total Quantity],
			    BLANK()
			)
			
			
			```
		formatString: 0
		lineageTag: e9004cd5-0d4a-472d-bfbd-47e145ee9fdc

	measure '_04 △PM% Total Quantity' = ```
			
			IF(
			    ISBLANK([_01 Total Quantity]) || [_01 Total Quantity] = 0,
			    "--",
			    DIVIDE([_01 Total Quantity] - [_02 PM Total Quantity], [_02 PM Total Quantity], 0)
			)
			
			
			```
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: d28bcdb4-38d5-47c4-b0cc-117e92ac8944

	measure '_04 △PY% Total Quantity' = ```
			
			IF(
			    ISBLANK([_01 Total Quantity]) || [_01 Total Quantity] = 0,
			    "--",
			    DIVIDE([_01 Total Quantity] - [_02 PY Total Quantity], [_02 PY Total Quantity], 0)
			)
			
			
			```
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 08752956-34cb-4ba6-ab4d-0c3d248da13b

	measure '_05 CF_△PY% Total Quantity' = ```
			
			SWITCH(
			    TRUE(),
			    [_04 △PY% Total Quantity] > 0, "#6A994E",
			    [_04 △PY% Total Quantity] = 0, "#808080",
			    "#BC4749"
			)
			
			
			```
		lineageTag: ac0bba21-9693-41b6-a517-18fc3137a437

	measure '_05 CF_△PM% Total Quantity' = ```
			
			SWITCH(
			    TRUE(),
			    [_04 △PM% Total Quantity] > 0, "#6A994E",
			    [_04 △PM% Total Quantity] = 0, "#808080",
			    "#BC4749"
			)
			
			
			```
		lineageTag: 52cd5269-860e-40df-9517-c1d0046047e4

	measure '_01 AC Total Quantity (DayNum)' = ```
			
			SUMX(
			    VALUES(Dates[Day]),  -- Ensures daynum remain visible
			    VAR TransactionsAC = COALESCE([_01 Total Quantity], 0)
			    RETURN 
			        TransactionsAC  -- Keeps 0 values visible
			)
			
			
			```
		formatString: 0
		lineageTag: 321a7dd0-bd0e-443a-8af6-d27f8aa3642d

	measure '_01 Max_Dynamic Selected Metric (DayNum)' = ```
			
			VAR max_val = 
			MAXX(
			    ALLSELECTED(Dates[Day]),
			    [_01 Dynamic Selected Metric (based on selected Metric card - DayNum)]
			)
			VAR check = IF(max_val = [_01 Dynamic Selected Metric (based on selected Metric card - DayNum)], max_val, BLANK() )
			RETURN
			check
			
			
			```
		lineageTag: 50052bba-d782-4c6e-99eb-8cad7532a31f

	measure '_01 Max_Dynamic Selected Metric (DayNum) - Dummy' = ```
			[_01 Max_Dynamic Selected Metric (DayNum)]
			
			
			```
		formatString: 0
		lineageTag: 1297aa84-f85f-4c33-8f65-383c0e202cd7

	measure Baseline = ```
			0
			
			
			```
		formatString: 0
		lineageTag: 312a1d94-97de-4675-b016-08e96de7a71b

	measure '_01 SVG Bar Chart_Total Transactions (based on selected dimension)' = ```
			
			VAR SelectedDimension = 
			    SWITCH(
			        TRUE(),
			        ISINSCOPE('vw_dim_customers'[customer_id]), "Customer",
			        ISINSCOPE('vw_dim_products'[product_id]), "Product",
			        "None"
			    )
			
			VAR IsTotal = 
			    SWITCH(
			        SelectedDimension,
			        "Customer", ISINSCOPE('vw_dim_customers'[customer_id]) = FALSE,
			        "Product", ISINSCOPE('vw_dim_products'[product_id]) = FALSE,
			        TRUE()
			    )
			
			VAR MaxTransaction = CALCULATE(
			    MAXX(ALL(vw_fact_sales), [_01 Total Transactions])
			)
			
			VAR Bar_Value = [_01 Total Transactions]
			VAR NormalizedValue = DIVIDE(Bar_Value, MaxTransaction)
			VAR Bar_Fill = NormalizedValue * 10
			
			VAR SVG_Data_URL = "data:image/svg+xml;utf8,"
			VAR SVG_Start = "<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 175 20'>"
			VAR SVG_Data = "<rect fill='#024AB2' x='0' y='0' width='" & Bar_Fill & "' height='20' />"
			VAR SVG_End = "</svg>"
			
			RETURN
			IF(
			    IsTotal || SelectedDimension = "None",
			    BLANK(),
			    SVG_Data_URL & SVG_Start & SVG_Data & SVG_End
			)
			
			```
		lineageTag: d6400628-69ee-4536-8d3f-c50936fe81ee

	measure '_03 SVG Bar Chart_Total Order Value (based on selected dimension)' = ```
			
			VAR SelectedDimension = 
			    SWITCH(
			        TRUE(),
			        ISINSCOPE('vw_dim_customers'[customer_id]), "Customer",
			        ISINSCOPE('vw_dim_products'[product_id]), "Product",
			        "None"
			    )
			
			VAR IsTotal = 
			    SWITCH(
			        SelectedDimension,
			        "Customer", ISINSCOPE('vw_dim_customers'[customer_id]) = FALSE,
			        "Product", ISINSCOPE('vw_dim_products'[product_id]) = FALSE,
			        TRUE()
			    )
			
			VAR MaxRevenue = CALCULATE(
			    MAXX(ALL(vw_fact_sales), [_01 Total Revenue])
			)
			
			VAR Bar_Value = [_01 Total Revenue]
			VAR NormalizedValue = DIVIDE(Bar_Value, MaxRevenue)
			VAR Bar_Fill = NormalizedValue * 200
			
			VAR SVG_Data_URL = "data:image/svg+xml;utf8,"
			VAR SVG_Start = "<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 175 20'>"
			VAR SVG_Data = "<rect fill='#024AB2' x='0' y='0' width='" & Bar_Fill & "' height='20' />"
			VAR SVG_End = "</svg>"
			
			RETURN
			IF(
			    IsTotal || SelectedDimension = "None",
			    BLANK(),
			    SVG_Data_URL & SVG_Start & SVG_Data & SVG_End
			)
			
			```
		lineageTag: 1dd45437-5934-4de1-b809-ce73f70a9cb0

	measure '_01 Dynamic Selected Metric (based on selected metric card - DayNum)' = ```
			
			VAR _SelectedMetricOrder = SELECTEDVALUE('PMetric'[PMetric Order])
			RETURN
			    SWITCH(
			        _SelectedMetricOrder,
			        0, [_01 AC Total Profit (DayNum)],
			        1, [_01 AC Total Quantity (DayNum)],
			        2, [_01 AC Total Revenue (DayNum)],
			        3, [_01 AC Total Transactions (DayNum)],
			        BLANK()
			    )
			
			
			```
		formatString: 0
		lineageTag: 9778424e-d933-4430-b7d8-5250c3e089e4

	measure '_01 Dynamic Selected Line Chart Title (based on selected metric)' = ```
			
			VAR _SelectedVariableOrder = SELECTEDVALUE('PMetric'[PMetric Order])
			
			RETURN
			SWITCH(
			    _SelectedVariableOrder,
			    
			    -- Transaction Metrics
			    0, "Daily Profit Trends",
			    
			    -- Revenue Metrics  
			    1, "Daily Quantity Trends",
			    
			    -- Profit Metrics
			    2, "Daily Revenue Trends",
			
			    -- Quantity Metrics
			    3, "Daily Transaction Trends",
			    
			    -- Default when no selection
			    "Daily Trends"
			)
			
			
			```
		lineageTag: b1718006-6859-4d53-9627-404ad2696a49

	measure 'Y-Axis Max_Dynamic Selected Metric (DayNum)' = ```
			
			VAR _SelectedMetric = SELECTEDVALUE(PMetric[PMetric Order])
			VAR _HighestValue =
			    SWITCH(
			        _SelectedMetric,
			        // Transaction Metrics
			        0, MAXX(ALLSELECTED('Dates'[Day]), [_01 Total Profit]),
			
			        // Revenue Metrics
			        1, MAXX(ALLSELECTED('Dates'[Day]), [_01 Total Quantity]),
			
			        // Profit Metrics
			        2, MAXX(ALLSELECTED('Dates'[Day]), [_01 Total Revenue]),
			
			        // Quantity Metrics
			        3, MAXX(ALLSELECTED('Dates'[Day]), [_01 Total Transactions]),
			
			        // Default when no selection
			        BLANK()
			    )
			RETURN
			    IF(
			        NOT ISBLANK(_HighestValue),
			        _HighestValue * 1.5
			    )
			
			
			```
		lineageTag: f15f898e-e680-4bcc-819f-93c722826d19

	measure '_01 Dynamic Selected Metric (based on selected metric card)' = ```
			
			VAR _SelectedMetricOrder = SELECTEDVALUE('PMetric'[PMetric Order])
			RETURN
			    SWITCH(
			        _SelectedMetricOrder,
			        0, [_01 Total Profit],
			        1, [_01 Total Quantity],
			        2, [_01 Total Revenue],
			        3, [_01 Total Transactions],
			        BLANK()
			    )
			
			
			```
		formatString: 0
		lineageTag: a8ab6fc8-92f6-42f5-9d15-09d077e41fa2

	measure '_01 Dynamic Selected Table Subtitle (based on selected metric card - for showing top 5 states)' = ```
			
			VAR _SelectedVariableOrder = SELECTEDVALUE('PMetric'[PMetric Order])
			
			RETURN
			SWITCH(
			    _SelectedVariableOrder,
			    
			    -- Transaction Metrics
			    0, "by Total Transactions",
			    
			    -- Revenue Metrics  
			    1, "by Total Revenue",
			    
			    -- Profit Metrics
			    2, "by Total Profit",
			
			    -- Quantity Metrics
			    3, "by Total Quantity",
			    
			    -- Default when no selection
			    ""
			)
			
			
			```
		lineageTag: 0ce8957c-7e9d-43ea-ac08-7479584ec49c

	measure '_03 Dynamic Selected Dimension Name (based on selected dimension ID)' = ```
			
			VAR _SelectedVariableOrder = SELECTEDVALUE('PDimensionID'[PDimensionID Order])
			RETURN
			    SWITCH(
			        _SelectedVariableOrder,
			        0, SELECTEDVALUE(vw_dim_customers[last_name]),    -- Show selected customer name
			        1, SELECTEDVALUE(vw_dim_products[product_name]),      -- Show selected product name
			        BLANK()
			    )
			
			```
		lineageTag: 7b00d344-21c4-4f36-a073-1403fcc8e780

	measure '_01 Dynamic Selected Paginated Table Title (based on selected dimension)' = ```
			
			VAR _SelectedVariableOrder = SELECTEDVALUE('PDimensionID'[PDimensionID Order])
			
			RETURN
			SWITCH(
			    _SelectedVariableOrder,
			    
			    -- Dimension: Customer
			    0, "Customer Order Summary",
			    
			    -- Dimension: Product 
			    1, "Product Order Summary",
			    
			    -- Default when no selection
			    "Daily Trends"
			)
			
			```
		lineageTag: 4810f5b7-087f-44ac-a346-a318b97e18e6

	column Value
		dataType: int64
		formatString: 0
		lineageTag: 50178183-5a39-4643-b675-2afec83cd05b
		summarizeBy: sum
		sourceColumn: Value

	partition _measures = entity
		mode: directLake
		source
			entityName: _measures
			expressionSource: DatabaseQuery

